version: '3'
services:

  mongoDB:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=A123a123
    volumes:
      - StickyNoteAPP-Data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=A123a123
      - ME_CONFIG_MONGODB_SERVER=mongoDB
    restart: on-failure

  StickyNoteAPP:
    image: stickynote_app
    ports:
      - 2999:2999
    environment:
      - MONGO_SERVER=stickynote_mongoDB_1
volumes:
  StickyNoteAPP-Data:
    driver: local
